basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        led.stopAnimation()
        led.plot(0, 0)
        led.plot(1, 1)
        led.plot(4, 0)
        led.plot(3, 1)
        led.plot(2, 2)
        led.plot(1, 3)
        led.plot(3, 3)
        led.plot(0, 4)
        led.plot(4, 4)
    } else {
        led.stopAnimation()
        led.plot(1, 0)
        led.plot(2, 0)
        led.plot(3, 0)
        led.plot(0, 1)
        led.plot(0, 2)
        led.plot(0, 3)
        led.plot(1, 4)
        led.plot(2, 4)
        led.plot(3, 4)
        led.plot(4, 1)
        led.plot(4, 2)
        led.plot(4, 3)
    }
})
